build:
		gcc main.c ./src/arithamatic_operations/Adition.c ./src/arithamatic_operations/Substraction.c ./src/arithamatic_operations/Division.c ./src/arithamatic_operations/Multiplication.c ./src/Calculator/ApplyOperation.c ./src/Calculator/Evaluate.c ./src/Calculator/Precedence.c ./src/ValidateExpression.c -o calculator

run:
		./calculator

clean: 
		rm calculator
